### ISSUE TITLE
[Bug] addRequiredStagesWithModifier only multiplies once

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/Elemental-Research#12]
```JAVA
var earth_1 = Util.createEntry("Earth 1");
earth_1.setIcon(<minecraft:grass>);
earth_1.description = "Unlocks a new Gamestage";
earth_1.earthCost = 20;
earth_1.experienceGiven = 2;
earth_1.addRequiredStagesWithModifier("OR", 2.0, ["air_1", "fire_1", "water_1", "wood"]);
earth_1.addGivenStage("earth_1");
earth_1.build();
```

it should multiply the costs for each of the unlocked quests in the array and not only once if any of them gets unlocked.

**Comment by ghost** [comment]
In 1.3.0 i've added "FOREACH_OR" and "FOREACH_AND" which gives the behavior you desire. "OR" and "AND" use standard boolean logic and will continue to only apply the modifier once as long as the AND/OR condition is met
