### ISSUE TITLE
[Suggestion] add a config file

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/Elemental-Research#8]
- change the amount of jumps for 1 air point
- white / blacklist blocks for earth points
- change the amount of earth points gained for specific blocks (`minecraft:obsidian-25`)
- disable point collection at all (not needed for divine equilibrium but i have something in mind) so points can only be obtained by buying them
- set the amount of fire points you get for receiving 1 burning damage
- set the amount of water points you get for receiving 1 drowning damage

**Comment by ghost** [comment]
Added in 1.3.0. For earth, I didn't explicitly add a blacklist/whitelist but I did a list config in the format 
``<mod>:<itemname>:<meta>:<points>`` or ``<mod>:<itemname>:<points>``
i.e. ``minecraft:obsidian:25`` 

You can effectively blacklist blocks by setting their point value to 0.
