### ISSUE TITLE
Fix Research description

### ISSUE THREAD

**Issue by MasterEnderman** [al132mc/Elemental-Research#9]
![image](https://user-images.githubusercontent.com/24524662/61029230-da1ba480-a3ba-11e9-8dd5-7e5c7153db0d.png)

- replace "XP" with bottle o enchanting
- move research description a few pixels over

**Comment by ghost** [comment]
Added XP icon and adjusted the description and such a bit in v1.3.0 Now the numbers won't clash until they reach the 1000s
